apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: postgres-operator
type: Opaque
data:
  username: a2V5Y2xvYWtfYWRtaW4= # keycloak_admin (Base64 encoded)
  password: S2V5Y2xvYWtBZG1pblBhc3N3b3JkMTIz # KeycloakAdminPassword123 (Base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: dicom-admin-secret
  namespace: postgres-operator
type: Opaque
data:
  username: ZGljb21fYWRtaW4= # dicom_admin (Base64 encoded)
  password: RGljb21BZG1pblBhc3N3b3JkMTIz # DicomAdminPassword123 (Base64 encoded)
