apiVersion: batch/v1
kind: Job
metadata:
  name: create-databases
  namespace: postgres
spec:
  template:
    spec:
      containers:
      - name: create-databases
        image: postgres:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        command:
        - psql
        args:
        - -h
        - postgres-rw.postgres.svc.cluster.local
        - -U
        - postgres
        - -c
        - |
          CREATE DATABASE keycloak;
          CREATE USER keycloak_admin WITH ENCRYPTED PASSWORD 'KeycloakAdminPassword123';
          GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak_admin;

          CREATE DATABASE dicom_store;
          CREATE USER dicom_admin WITH ENCRYPTED PASSWORD 'DicomAdminPassword123';
          GRANT ALL PRIVILEGES ON DATABASE dicom_store TO dicom_admin;
      restartPolicy: Never
  backoffLimit: 3
