apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-secret
  storage:
    size: 10Gi
    storageClass: standard
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgres-secret
