apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  password: cG9zdGdyZXM=  # Base64 encoded password (e.g., "postgres")

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: postgres
type: Opaque
data:
  password: S2V5Y2xvYWtBZG1pblBhc3N3b3JkMTIz  # Base64 encoded password (e.g., "KeycloakAdminPassword123")

---
apiVersion: v1
kind: Secret
metadata:
  name: dicom-admin-secret
  namespace: postgres
type: Opaque
data:
  password: RGljb21BZG1pblBhc3N3b3JkMTIz  # Base64 encoded password (e.g., "DicomAdminPassword123")