apiVersion: batch/v1
kind: Job
metadata:
  name: create-keycloak-database
  namespace: postgres
spec:
  template:
    spec:
      containers:
        - name: create-keycloak-db
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          command: ["psql"]
          args:
            - -h
            - postgres-rw
            - -U
            - postgres
            - -c
            - |
              CREATE DATABASE keycloak;
              CREATE USER keycloak_admin WITH ENCRYPTED PASSWORD 'KeycloakAdminPassword123';
              GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak_admin;
      restartPolicy: Never
