apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: blackford-platform-ns
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30458
  selector:
    app: pgadmin
  type: NodePort
